lib/components/Button.tsx

Fixing problems I come across with converting https://github.com/sojourn-13/sojourn-station/ to use tgui-core
Currently included:
- Buttons shouldn't put a margin on their icons if there is no text/html to display

Fixes/Tweaks from Sojourn Conversion 

---

README.md

small improvement to the readme

---

.github/workflows/pr.yml

Basic GitHub Actions Workflow

---

.github/workflows/release.yml

Make the release workflow work for draft releases too

Make the release workflow work for draft releases too

---

lib/components/TimeDisplay.tsx

oop, reviews somehow missed this, only saw it in the compiled dist lol

Removes dumb console.log i forgot in TimeDisplay

---

lib/components/Box.tsx

Add onMouseLeave to <Box>

---

lib/components/Slider.tsx

**Slider**
-> Adds the disabled prop back in, so that the compiler won't complain when one tries to disable it

Add disabled prop to slider

---

lib/components/Divider.tsx

Ya copy pasted the wrong comment mr guy
Fixed comment

Fixes divider comment

---

package.json

Importing via `pkg:tgui-core/styles/components/Button` wasn't working
Bug fix

Fixes sass export

---

.storybook/preview.scss

I don't know how it happened, most likely the branch was with the old style location, so I didn't notice it
Storybook works again

Fix Storybook styles import

---

lib/common/string.ts

Adds the trademark and copyright sign to the decoded html entity list.
In some UIs, fictional companies or web pages exist, using the copy and trade mark signs in game. This allows decodeHtmlEntities to display them

We sometimes have fictional companies

---

lib/components/Chart.tsx

Old chart has a dead ref. Idk why and i don't give a fuck about class components, soo... i just moved it to functional component and used ref.
Work's now but untested on 515
Fixes #72 
https://github.com/user-attachments/assets/6be71103-a95a-436b-a97f-9f0c2911bd3a

Fix `Chart` on WebView2

---

package.json
pnpm-workspace.yaml

Tried setting the project version to pnpm v10. Found a [bug](https://github.com/nodejs/corepack/issues/612). Hoping this doesn't break installs for anyone - if so, [install pnpm directly](https://pnpm.io/installation) rather than through corepack 
I can use pnpm v10

Updates pnpm

---

lib/components/Button.tsx
lib/components/Dropdown.tsx
lib/components/Floating.tsx
lib/components/ImageButton.tsx
lib/components/MenuBar.tsx
lib/components/Tooltip.tsx
stories/Button.stories.tsx
stories/Tooltip.stories.tsx
styles/components/Floating.scss
styles/components/MenuBar.scss
styles/components/Tooltip.scss
styles/vars-components.scss

Swaps out popper for floating component. Significant code reduction here. @AyIong said this caused some layout breakage, so this needs further testing
Uh our tooltip code is made 100% less hacky

Tooltip: Popper -> Floating

---

lib/components/Floating.tsx
lib/components/Tooltip.tsx
styles/components/Floating.scss

We shouldn't need to change the css just to fix where it was appearing
@AyIong try this
Bug fix

Fixes tooltip children layout

---

lib/components/Button.tsx
lib/components/Section.tsx
lib/components/TextArea.tsx
styles/components/TextArea.scss

No need to use these
Forwardref is useless in react 19

Removed forward refs

---

lib/components/ImageButton.tsx
styles/components/ImageButton.scss
styles/vars-components.scss

I got back what I deleted because I forgot why it was needed, like noAction.
Also brought back the transparent color, which I think I did, but I don't remember if I did a PR on it, and also added a primary color, fixed buttons positioning and border if no content
I accidentally beat my child 28 times, and now I'm hanging patches on him
Hopefully no more style fixes will be needed as I'm sure jlsnow is tired of watching this by now

Return some removed from ImageButton styles

---

lib/common/eventbus.ts

Preview for the new tgui backend that I'm working on.
TGUI's state management solution is on the way out. This provides a nice event dispatcher for everyone

Adds event bus

---

lib/components/RestrictedInput.tsx

Guh, this time I managed to forget about the state change... We ofc should send the next state value back and not the current one...

sends the right value to onChange on restrictedInput negation

---

.github/workflows/publish_storybook.yml
.storybook/main.ts

Makes storybook atuomatically deploy to github pages.
Needs repo pages configuration set to deploy from github actions.

Adds storybook to github pages

---

lib/components/Autofocus.tsx
lib/components/Blink.tsx
lib/components/Box.tsx
lib/components/Dialog.tsx
lib/components/DmIcon.tsx
lib/components/Image.tsx
lib/components/LabeledList.tsx
lib/components/Modal.tsx
lib/components/NoticeBox.tsx
lib/components/TrackOutsideClicks.tsx
stories/TrackOutsideClicks.stories.tsx

Converted blink and trackoutsideclicks to a function component
Added more documentation & a story to trackoutside
Better ux. Part of #122

Some quick updates, class component removals

---

global.d.ts
lib/common/hotkeys.ts

To address https://github.com/tgstation/tgstation/issues/91198

Allows you to specify how parameters are injected to hotkey passthrough

---

.github/copilot-instructions.md
.vscode/settings.json
lib/components/Popper.tsx

You can customize copilot chat responses with natural language which will be fed into the conversation for context.
https://code.visualstudio.com/docs/copilot/copilot-customization#_use-a-githubcopilotinstructionsmd-file
It might stop suggesting things that you have to fix because you know something it doesn't

Experimental: Adds copilot default instructions

---

lib/components/InfinitePlane.tsx

I fucked up and for some reason swapped these in the last version
Behaviors oppositely to how you'd expect it to

Fixes inverse scrollwheel behavior on InfinitePlane

---

lib/common/events.ts
lib/common/hotkeys.ts

As seen here <https://github.com/BeeStation/BeeStation-Hornet/pull/12834>
Credit to PowerfulBacon if so (not tagged to prevent notification spam)
Seems to completely fix their issue

Ports bee's tgui passthrough solution

---

lib/components/Button.tsx

If you use an expression which results in false, button would not be passed a color, even default
Bug feex

Hot fix for falsy button colors

---

biome.json
bun.lock
package.json

Updates biome to full release

---

README.md

Adds build instruction
Was really annoying for a noobie to figure out how to build

Add build instruction
