lib/common/string.ts

title, should be useful
currently we use `export const pluralize = (word: string, n: number) => (n !== 1 ? word + 's' : word);` which is nice but this Should Work for 99.9% of words now
okay yes technically fucky words like `soliloquy` aren't supported but english is fucked
thought `VOWELS` might be useful for consumers

pluralize function for common/string

---

lib/components/TimeDisplay.jsx

This lets interfaces pass a formatting function in case they want to format time differently
(See: no hour digits)
needs to be converted to typescript and not this weirdness but out of scope
edit: guh accidentally pushing unsaved versions every time

Add `format` prop to timedisplay

---

.github/workflows/release.yml
README.md

Use is documented in the README. Should be fairly simple, you just create an empty release with the version you want as a tag and it set to the latest commit. The action will fill out the release details, which you could edit after if you wanted.
Ends up looking somewhat like this, after publishing a release targeting that merge commit:
Need to create a repository secret named `NPM_TOKEN` with the npm push token in it.
I guess we should formalize not pushing built dist files? Maybe a precommit hook?

Release Workflow

---

.github/workflows/release.yml

This prevents us from running into the required pull requests instead of pushing to main, because the service account is whitelisted to push directly.

Publishing is now done via service account

---

lib/components/LabeledList.tsx

>  `Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.`
https://github.com/facebook/react/issues/5652
therefore, to stop the error, commit

validateDOMNesting(...): <tr> cannot appear as a child of <table>

---

lib/components/Box.tsx

you successfully got `mt`/`marginTop` directly, but not `my` and etc which still was producing `margin-Top` causing
> `Warning: Unsupported style property margin-Top. Did you mean marginTop?`

directional unit BLUNDER

---

lib/components/ColorBox.tsx

Is this intended?
unsure why there's a random period in the middle of the color box square
this changes it to

Weird ColorBox dot

---

lib/components/Button.tsx
lib/components/Collapsible.tsx
lib/components/Input.tsx
lib/components/NoticeBox.tsx
lib/components/NumberInput.tsx
lib/components/Section.tsx
lib/components/Tabs.tsx
lib/components/TextArea.tsx
lib/styles/components/Section.module.scss
lib/styles/components/Section.module.scss.d.ts

Likely a lot to discuss and some things might get stripped, but after trying to update our UIs to tgui core, I've had quite a few issues:
**Button**:
-> Adds the option to resize the icon given to the button
**Collapsible**:
-> Adds the option to adjust the child_mt which had been statically set to 1, it's now defaulted to 1 and freely adjustable as param
**Input**:
-> Fixes the input not updating on component updates. This allows it to once more update the text when it's changed in the backend or in a state whilst the user is not focussing the field
**NoticeBox**:
-> Somewhere in time, the warning property had been lost, this adds it back to allow for orange warning boxes again
**Section**:
-> The use of forwardRef had caused scrolling issues with multiple scrollbars. Use ref allows for …

UI edits and changes from VS

---

lib/components/Box.tsx

I'm not sure why we don't have it there. This is used in a lot of places.

Adds `id` prop to <Box>

---

lib/components/DraggableControl.jsx
lib/components/NumberInput.tsx

**NumberInput**
-> Fixed an issue where the movement position was updated before one could reach the needed step pixels
-> Fixed an issue with float value steps not updating properly
-> Changed the focus timeout from 1 to 10 as for example in the chat, 1 was too fast
**DraggableControl**
-> Should Focus the input on clicks again like NumberInput

Number input fix

---

lib/components/ImageButton.tsx

Imagebutton previously had very global classnames bc scss modules and all.
Probably not great to let the styles bleed elsewhere
Yes, link: https://github.com/tgstation/tgui-styles/pull/5

Fixes imagebutton classnames

---

lib/components/Section.tsx

Fixes casing/naming convention on some section classnames
They do not match what is in tgui-styles. This normalizes the naming convention && matches names
Soon, link: https://github.com/tgstation/tgui-styles/pull/4

Fixes missed section tags

---

.storybook/main.ts
.storybook/preview-head.html
lib/components/Input.tsx
package.json
pnpm-lock.yaml
stories/Input.stories.tsx

#32 was failing because we don't create the `Byond` object in the test environment. Added this
I also noticed a discrepancy with our Inputs vs tgstation, where this fell through the cracks: https://github.com/tgstation/tgstation/pull/86495
I should note that in the above PR it broke the [rules of hooks ](https://react.dev/reference/rules/rules-of-hooks). I fixed this, it should still work as intended, and appears to do so in storybook. I added some nice test cases for input states, which is easily our most annoying component. I also added console logging to storybook via an addon https://storybook.js.org/addons/@storybook/addon-console
Fixes CI in #32 so we can merge
Parity with tgstation inputs
N/A

Fixes input, adds byond global

---

lib/components/Image.tsx

Edge ignores -ms-interpolation-mode, the standard way to do this is image-rendering: pixelated. Won't have adverse affects on IE, it'll just ignore the property.
fixBlur should work under 516 too.
Nope.

Set image-rendering for 516

---

lib/components/Section.tsx

Readds ref forwarding, but adds a fallback ref if none is provided. This should let us use refs without causing any issues with scroll on hover.
Note: #18 removed these as faulty. It'd be worthwhile to test these more to see if the behavior is working as intended.
Puts us at parity with TG so we can delete the components there. It's very confusing to have two different sets.
N/A

Readds section refs

---

lib/common/ui.ts
lib/components/Box.tsx
lib/components/Button.tsx
lib/components/Collapsible.tsx
lib/components/ColorBox.tsx
lib/components/Dialog.tsx
lib/components/Dimmer.tsx
lib/components/Divider.tsx
lib/components/DmIcon.tsx
lib/components/Dropdown.tsx
lib/components/Flex.tsx
lib/components/Icon.tsx
lib/components/Image.tsx
lib/components/ImageButton.tsx
lib/components/KeyListener.tsx
lib/components/LabeledControls.tsx
lib/components/LabeledList.tsx
lib/components/MenuBar.tsx
lib/components/Modal.tsx
lib/components/NoticeBox.tsx
lib/components/NumberInput.tsx
lib/components/ProgressBar.tsx
lib/components/Slider.tsx
lib/components/Stack.tsx
lib/components/Table.tsx
lib/components/Tabs.tsx
lib/components/Tooltip.tsx

All relevant documentation from the component reference is now ported onto the components themselves, meaning you can read the documentation by just hovering over the component or prop.
I also took a minute to remove some exports from `MenuBar`, `Table`, and `Dialog`. A bit confusing. In the future, components should only export their parent and link to any child components using the `Parent.Child = Child` syntax.
I also deprecated Flex, which really only has its use in circumventing the styling of `Stack`, but both should be redone for 516.
Observability ++
Code cleanup
Closes #43

Converts all component reference to TS docs + and some fixes

---

lib/components/Button.tsx
stories/Button.stories.tsx

It was bothering me. It seems just a smidge over too far for a button that feels compact.
Before:
After:
+ Added to button story
UI appearance

Adjusts the spacing on button icons

---

lib/components/Dropdown.tsx

Fix situation when autoscroll in Dropdown moves all content to the top, hiding Dropdown itself.
Also renamed the `scrollTo` function to `scrollToElement`, since the former is the default function in JS
<details><summary>Video</summary>
https://github.com/user-attachments/assets/0fef024b-5ef8-488c-81e8-ccf173e1c74f
</details>
Fixing an annoying thing. Focus is still not returning, but I don't want to go to war with how focus is handled in IE
Partial fix - https://github.com/tgstation/tgstation/issues/88857

Fix Dropown autoscroll

---

lib/components/DmIcon.tsx
lib/components/ImageButton.tsx
lib/styles/components/ImageButton.scss
stories/ImageButton.stories.tsx

- The `buttonsAlt` prop is no longer a boolean, but exactly the same as `buttons`, except for some little things before. 
What does it do? The ability to use them together, which is extremely useful in non-fluid mode, giving you the ability to stuff more information into the element.
- Exported `Direction` enum in `DmIcon` and added `dmDirection` prop into `ImageButton`, full integration now
- Small indentation reducion in styles
- Created some stories for component
Little component polish, due to which there are now likely to be even fewer situations where there isn't room for the right information, if anyone was stopped by that (like me)
Tested on 515 too
<details><summary>Video</summary>
https://github.com/user-attachments/assets/39ee62fa-96a7-4d33-9169-96a5f2aa7901
</details

Little `ImageButton` tweaks

---

lib/components/AnimatedNumber.tsx
lib/components/Button.tsx
lib/components/Icon.tsx
lib/components/ImageButton.tsx
lib/components/LabeledList.tsx
lib/components/Table.tsx
lib/components/Tabs.tsx

First change
Apparently bundling removes type information from items using the `Button.Input` style. This PR makes button into an exported namespace as a workaround to preserve the nested definition
Second
ImageButton was using a nested component, I moved this out, simplifying it and making it more idiomatic to react
Third
Some style changes
Better type definitions & better code

Better docs, some cleanup

---

lib/components/Collapsible.tsx
stories/Collapsible.stories.tsx

Just allows to set custom styles for Collapsible child. Optional.
The ability to do something like this:

Allow to set child styles in `Collapsible`

---

README.md
package.json

The documentation between sass and webpack seem to conflict. For this iteration, we're just relying on webpack to do the importing 
So we can properly deprecate tgui-styles

Fixes sass again

---

.storybook/preview.scss
.storybook/preview.ts
.storybook/previewTheme.ts
package.json
pnpm-lock.yaml

Changed the Storybook theme to a dark theme, since the TGUI components were originally made for a dark theme.
Debug and view components in a slightly more truthful environment, rather than on a white background
<details><summary> Video </summary>
Idk how to fix flickering
https://github.com/user-attachments/assets/0f96aa58-5ff6-4d88-96fa-c2a3b0519880
</details>

Paint storybook to dark

---

lib/components/Button.tsx
stories/Button.stories.tsx

Button styles have negative indentation at the icons, which is overwritten by 0 when checking if there is content, because of which the “extra” indentation appears
Extra padding look's really weird
Fixes #49

Fixes icon-only button extra padding

---

lib/components/ImageButton.tsx
stories/ImageButton.stories.tsx

ImageButton border radius fix.
I screwed up and didn't notice a bug that made the border radius on the right side of the button only go away if buttonsAlt is used, while it stays if the regular buttons container is used, which is why this happens:
Bugs bad

Fix ImageButton border radius

---

lib/components/Image.tsx
lib/components/ImageButton.tsx
styles/components/ImageButton.scss

Added asset scaling to the ImageButton component, it's not as handy as scaling normal images, but better than nothing.
On the downside - you have to specify the original size of the asset if it differs from 32x32
Also:
- Fixed question fallback size, it ignored the size of the image.
- Moved the assets down, as a result the order of image display is as follows if all possible props are filled in: base64 -> imageSrc (src of Image component) -> DmIcon -> asset (className)
- Buttons container will take disabled color if component disabled
- Added text shadow to buttonsAlt container into non-fluid component. Better text readability
And little fix for `Image` component.
On the 516 when the asset is used, the src is not filled, that's causing the “broken” image icon to be displayed.
Now if src …

Add asset image scaling to `ImageButton`

---

lib/components/Flex.tsx

Renames `inline` prop into the Flex component to `inlineFlex`, cause just inline conflicts with Box prop
Fix #64

Fix `inline` prop conflict

---

styles/components/Dimmer.scss
styles/components/Tooltip.scss

I ran into a situation where the Dimmer didn't cover everything below it.
The new z-indexes should prevent this from happening in the future, not only with Dimmer but also with Tooltips
Dimmer must cover everything bellow it, as well as tooltips should be over everything

Bump `Dimmer` & `Tooltip` z-index

---

lib/components/Modal.tsx

Allows us to forward the escape and enter events from modal windows. This will allow for example text inputs used within a modal to be confirmed with enter or close with escape instead of needing to press any button.
We've quite a few modal inputs in use, where input fields are generated dynamically.

allows some events from modal

---

lib/common/keys.ts

Ports a bunch of key input helpers... because I always was too lazy to check up to 8 keys at once in an if after keycodes became deprecated
If there's a better way to do this, let me know...
Less code needed if one wants to check for arrow inputs, movement inputs, etc.

bunch of key helpers

---

lib/components/InfinitePlane.tsx

This:
1. Converts InfinitePlane to TypeScript
1. TypeScript good

InfinitePlane Typescript

---

lib/common/collections.ts
tests/collection.test.ts

Implements a helper for string comparisons as localeCompare is not quite as performant as simply comparing the strings directly
It's a lot less to write using a function than to always do the full comparison

implements a string compare helper

---

lib/components/Input.tsx

OnPropsChange did update the input whenever the backend updated, this is not really a good idea when the input itself is focussed as returned input will fight with itself, leading to letters and words getting lost
It prevents that users fight with their own input into the textbox. Having it update and display text from other users in shared uis, etc is nice (especially for current search queries), but it shouldn't happen while entering text.

prevents input from being overridden while active

---

lib/common/ui.ts

Lowercases the directional properties in `computeBoxProps`
Chromium browsers are case sensitive when it comes to inline CSS properties, and will ignore the incorrectly formatted props such as `padding-Top`. This breaks the `px`, `py`, `mx`, and `my` props on Webview2.

Fix directional Box props on Chromium based browsers

---

lib/components/MenuBar.tsx

Menubars are functional components, so `this.menuRef` is undefined.
Uses the menuRef defined locally within the function.
I haven't tested this yet since I don't know how to
Fix bug

Fixes menubars not working

---

lib/components/Button.tsx

Back in the day, confirm buttons were reset whenever the focus was changed to prevent accidental confirms. This brings the old behaviour back.
fixes #89
No accidental confirmations because a confirm button kept its state.

Confirm buttons reset again on blur

---

lib/common/ui.ts
stories/Box.stories.tsx
stories/Stack.stories.tsx

As it turns out, when joined, the words 'padding' and 'left' do not become camel cased
Fixes one of those missable bugs that probably caused some gray hairs

padding & margins: I don't want to talk about, vol ii

---

lib/components/Button.tsx
package.json
styles/base.scss
styles/components/Button.scss
styles/components/ImageButton.scss
styles/components/Tabs.scss

> [!IMPORTANT]
> `$color-disabled` variable was removed from buttons. 
> DON'T forget to remove it from themes, if that's PR will be merged
Buttons now give more feedback:
1. When hovering, the cursor changes to pointer if the button can be clicked.
2. When a button is clicked, it will respond by sharply darkening the background, letting you know at once that the click has passed.
3. Disabled buttons are now semi-transparent instead of gray.
ImageButton got only cursors and click impact
Tabs got indicator animation
Let's hope i didn't break something a lot
P.S. transparent buttons now real transparent
<details> <summary> Demo </summary>
https://github.com/user-attachments/assets/c61a3108-5948-4c84-9a84-7ed84d43acca
https://github.com/user-attachments/assets/e86ba5b5-70b1-4d34-99ff-9149fe04 …

[516 ONLY] Improves buttons & tabs UX

---

lib/components/Dropdown.tsx
lib/components/Floating.tsx
styles/components/Dropdown.scss
styles/css-variables.scss
styles/main.scss

Moving dropdown from PopperJS to FloatingUI
And refactor styles, so it now don't looks fucked (need testing)
So, we have some new features and new look:
1. Dropdown menu now takes parent width, it can be disabled by prop, but enabled by default
2. Dropdown menu now look's more rounded and blurs content behind
3. Dropdown menu now "teleporting" like tooltips, outside app node to the root, which means it will not affected by `overflow: hidden`
4. Styles and layout refactor: Styles are now more readable and more robust, which should mean that dropdown will no longer look “crooked”.  Dropdown itself now has less nesting
Also added small animations, just why not, they don't lag like on IE
Another try to make Dropdown less fucked
| Before | After |
| - | - | 
| …

Dropdown v4: Floating Edition

---

lib/components/Dropdown.tsx
lib/components/Floating.tsx
stories/Dropdown.stories.tsx

Using useEffect here means we can get potentially more re-renders than we need. Also, it's doing some voodoo magic to make sure it works by pushing the DOM modifications to happen after reacts re-render, which is pretty risky.
This is generally the intended way, from reading the docs, on how to make modifications to the dom elements rendered by Floating. Check them here: https://floating-ui.com/docs/useFloating#whileelementsmounted
It would be fine to use a useEffect if the dropdown was not conditionally rendered, but in this case, it is so we need to use `whileElementsMounted`

Upgrades dropdowns to use whileElementsMounted instead of useEffect

---

styles/components/Button.scss

That was TOO bright on hover, idk why, maybe i fucked up it
But now it's ok
Eyes saving

Decrease `Button` lightness on hover

---

lib/components/Button.tsx
styles/components/Button.scss
styles/components/NoticeBox.scss

- Moved the NoticeBox colors to oklch, as hsl was adding a bluish tint to white and gray.
- Adds class to Button icon to prevent decreasing content padding, when using Icon component instead icon prop, like that:
```jsx
<Button fluid>
<Stack fill>
<Stack.Item grow>
Some Text
</Stack.Item>
<Stack.Item>
<Icon />
</Stack.Item>
</Stack>
</Button
```  
<details> <summary> NoticeBox </summary> 
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/923fae00-67dc-4e7d-bd3c-ee9dabff998c) | ![image](https://github.com/user-attachments/assets/ec2df61c-3095-408c-9661-43a6c6b27297) |
</details>
Gray must be gray
And button padding must look ok if you use Icon component instead prop, not like this:

Fix NoticeBox gray & white colors and Button padding when using Icon component inside

---

lib/components/RestrictedInput.tsx
stories/RestrictedInput.stories.tsx
styles/components/RestrictedInput.scss
styles/main.scss

Due to popular demand (one sole person asking me not to remove it), I've reimplemented restrictedInput
It should work the same with much less overhead, but I'm making its events match textarea (value only)
Requested

Rebuilds restrictedInput as a typescript FC

---

lib/components/ImageButton.tsx
styles/components/ImageButton.scss

That was... unusual
But fallback icons will not break layout now
Also allows to replace default fallback icon with something interesting, like...

Fix ImageButton fallback icon align

---

lib/components/InfinitePlane.tsx

I don't know why this is there, it may have been added accidentally, but it blocks any interaction with the content
Fixes https://github.com/tgstation/tgstation/issues/90603

Remove `pointer-events: none` in `InfinitePlane`

---

lib/components/RestrictedInput.tsx

When we negate a number, we also should expose that to onChange... otherwise, if we use the buttons to confirm on e.g. NumberInputModal, we get the previous non negated number as value...

fix neagtions on restricted input not getting updated directly

---

lib/components/Button.tsx
stories/Button.stories.tsx

I forgot to rework button.inputs in #139
It makes no sense for these to have some unique onCommit e,v event handler. It's now just like a normal input (under the button of course).
Note, it no longer accepts tooltips, or children props. Inputs do not get children. You shouldn't be able to add in a react component inside of this button
Standardization

Button inputs into new format

---

docs/component-reference.md
lib/components/Input.tsx
lib/components/RestrictedInput.tsx
lib/components/TextArea.tsx

Re-adds `onBlur` prop to `Input`, `TextArea`, and `RestrictedInput`.
Defaults `Input` inner state to an empty string if `value` is not provided, for type sanity.
Without `onBlur`, removing the event that lets us tell when a user is done messing with an input (and instead have to make do with `onChange` on every keypress), some user input patterns become harder to implement, e.g. non-annoying validation messages.

Re-add onBlur (with value arg) to Input, TextArea, RestrictedInput

---

lib/common/ui.ts
lib/components/Box.tsx
lib/components/Icon.tsx
lib/components/Input.tsx
lib/components/RestrictedInput.tsx
lib/components/Table.tsx
lib/components/TextArea.tsx
stories/Input.stories.tsx
stories/RestrictedInput.stories.tsx
stories/TextArea.stories.tsx

- Calls the `onKeyDown` prop when a key is pressed (i.e. `onKeyDown` on the appropriate control element), if provided, for `Input`, `TextArea`, and `RestrictedInput`.
- Types `BoxProps`' `EventHandlers` based on the target element type, defaults to `HTMLDivInput` (existing behavior).
- Adds stories for each to show the behavior. Uses console logging, as that seems to be the standard approach in `tgui-core`.
- `onKeyDown` is a valid prop for `Input`, `TextArea`, and `RestrictedInput` components, but the implementation silently swallow any passed in prop and don't use them, as they write their own `onKeyDown` implementation as part of their inner workings and don't call the one in the prop. This is misleading.
- Allowing more correct typing is a good thing, although it is somewhat up to the …

Wires up onKeyDown prop for Input, TextArea, and RestrictedInput

---

README.md
lib/common/color.ts
tests/color.test.ts

Color.fromHex ignores the alpha, this fixes it
Also added small blurbs for testing to readme since people didnt bother to document how to test
Converting back and forth should not lose data

Fixes Color.fromHex ignoring alpha

---

.github/copilot-instructions.md
.prettierrc.yml
biome.json
lib/common/collections.ts
lib/common/constants.ts
lib/common/events.ts
lib/common/format.ts
lib/common/fp.ts
lib/common/http.ts
lib/common/react.ts
lib/common/type-utils.ts
lib/common/types.d.ts
lib/common/ui.ts
lib/components/Autofocus.tsx
lib/components/Blink.tsx
lib/components/Box.tsx
tests/collection.test.ts

Removed some functions we weren't using, including some duplicates
Fixes #169
Converts boxprops to an interface since it's using excessive merge-fu.  https://github.com/microsoft/TypeScript/wiki/Performance/670a5543f4d478774aeffe1b3b0b86ed2eb8b4ff#preferring-interfaces-over-intersections
Everything is LF now
'Nobody uses these' / 'Irrelevant to our framework' seems like just reason to shave it off

Some cleanup

---

lib/components/ByondUi.tsx

this sends a message to dm when we render or unmount a byondui
i cover the why in https://github.com/tgstation/tgstation/pull/91389 but i'll admit it doesn't feel great having to pass this over to the game, and even worse doing this inside a library. but byonduis are already weird

sends a message to dm when byonduis are rendered/unrendered

---

lib/components/DraggableControl.tsx
lib/components/Knob.tsx
lib/components/Slider.tsx
stories/interfaces/common/InterfaceLockNoticeBox.jsx

Inconsistent documentation. It's now clear: onChange fires when released and input is typed in, onDrag fires while dragging.
Fixes #185
Clarity

Fixes docs on draggables

---

package.json
rslib.config.ts

Can't import atomic as it wasn't listed in package.json
This also removes cjs imports (not even a valid condition)
Bug fix

Fixes exports

---

lib/components/InfinitePlane.tsx
stories/components/InfinitePlane.stories.tsx

InfinitePlane now has slight transition animation to not snap as rapidly (disabled when its being dragged by a mouse), zoom now centers around the camera (when zooming using button controls) or the mouse (when using the scrollwheel). Also added ``zoomToX`` and ``zoomToY`` which when set force camera position to said coordinates.
Also min/max zoom and zoom increments are parameters instead of constants.
InfinitePlane sucks to use for players, and external position controls are needed for a dev tool I'm doing

Makes InfinitePlane smoother, fixes zoom centering around (0, 0) and implements external position controls

---

.storybook/main.ts
lib/common/ui.ts
lib/components/BlockQuote.tsx
lib/components/Box.tsx
lib/components/Button.tsx
lib/components/ByondUi.tsx
lib/components/Chart.tsx
lib/components/Collapsible.tsx
lib/components/ColorBox.tsx
lib/components/Dropdown.tsx
lib/components/Flex.tsx
lib/components/Icon.tsx
lib/components/ImageButton.tsx
lib/components/InfinitePlane.tsx
lib/components/Input.tsx
lib/components/Knob.tsx
lib/components/LabeledControls.tsx
lib/components/LabeledList.tsx
lib/components/Modal.tsx
lib/components/NoticeBox.tsx
lib/components/NumberInput.tsx
lib/components/ProgressBar.tsx
lib/components/RestrictedInput.tsx
lib/components/RoundGauge.tsx
lib/components/Section.tsx
lib/components/Slider.tsx
lib/components/Stack.tsx
lib/components/Table.tsx
lib/components/Tabs.tsx
lib/components/TextArea.tsx

We can exclude box props from other components. To make up for this, i added a link to inherited props via box in the components that do this.
Storybook is cool!
Fixes #204 
Just a minor inconvenience to have to sort through every box prop you've ever seen just to see what `onChange` takes on an input component, etc

Exclude box props from other components

---

lib/components/ProgressBar.tsx

- Made ProgressBar's `ranges` prop completely readonly
- Added support for fractional digits
- `readonly T` can be assigned to `T` but not the other way around. Ranges are often defined as constants, which are `readonly`. Therefore, TypeScript sometimes raises a type mismatch error when setting `ranges`. As such, I've changed `ranges` to be readonly
- added support for fractional digits for parity with Paradise station

Make ProgressBar `ranges` prop readonly and add support for fractional digits

---

styles/components/Section.scss

Changes the CSS to make scroll bars automatically appear in scrollable sections instead of forcing scroll bars for all scrollable sections, even if a scroll bar isn't needed because the content doesn't overflow
Note: this can not be trivially changed by consumers without touching the section component's internals
Scroll bars take up space and when they aren't needed they look odd. "scrollable" can't be removed from the section because the section would not scroll anymore even if content overflows

Do not force scroll bars in scrollable sections

---

lib/common/ui.ts
lib/components/Box.tsx

Exposes dragging event handlers and draggable HTML attribute. Also added a `satisfies` constraint on `eventHandlers` to ensure every item in the list is a real DOM attribute
Allows customization of component dragging. Fixes TypeScript errors with Paradise's map preferential voting system which uses dragging

Expose drag event handlers and draggable attribute

---

lib/components/DraggableControl.tsx
stories/components/LabeledControls.stories.tsx

- Fixes `tickWhileDragging` in combination with `onChange` on `DraggableControl`s causing the handler to receive the initial value instead of the current value
- Adds minimum and maximum values to the knobs in the LabeledControls story
- Passing the initial value in a handler meant to listen for changes isn't useful or intuitive
- The knobs in the LabeledControls story go to positive and negative infinity when used

Fix draggablecontrol tickwhiledragging
